export { Hero } from './Hero'
export { About } from './About'
export { Projects } from './Projects'
export { Experience } from './Experience'
export { Testimonials } from './Testimonials'
export { default as Contact } from './Contact'
